### ISSUE TITLE
meraki switch getDeviceSwitchPorts --serial

### ISSUE THREAD

**Issue by thaison82** [PackeTsar/meraki-cli#16]
Hello friends,
I want to use output of this command to display on remote monitor/LCD screen (for example to a remote Riser Room which has Meraki switch for engineer easier to watch), what is best way to approach this thing?
Many thanks.

**Comment by PackeTsar** [comment]
Are you wanting to just have the output table refresh every few seconds on a screen?

**Comment by thaison82** [comment]
Yes. I think it will refesh after few seconds is good.

**Comment by PackeTsar** [comment]
You can use the `watch` command like `watch meraki switch getDeviceSwitchPorts --serial XXXX-XXXX-XXXX` to do that kind of thing, but I just tested it and it looks like Meraki-CLI wants to output JSON data instead of a table when using `watch`. I may need to add a "force tabulation" switch to Meraki-CLI to make it work right. I'll look into this in the next day or two and get back to you.

**Comment by PackeTsar** [comment]
FYI: `watch` is a unix tool, but can also be installed on MacOS with `brew install watch`. It should also work for you on WSL. If you are running Meraki-CLI in native Windows command prompt, then I don't think `watch` will work for you.

**Comment by thaison82** [comment]
Thanks a ton.  I've already installed WSL and it works well with our meraki api and command getDeviceSwitchports.
What I'm in trouble is I don't know how to bring that table to remote screen.

**Comment by thaison82** [comment]
Maybe I'll use Flask and run meraki command inside, then use IP cast to remote smart TV.

**Comment by thaison82** [comment]
Hi John,
I used Flask successfully with Python-request API, then I converted to json and expose it to network by html.
Thanks a lot.
